export enum ComponentFormActionType {
    SET_FORM_STATE,
    SET_COMPONENT_TYPE_ID,
    SET_COMPONENT_NAME,

    SET_COMPONENT_PRODUCT_FORM_STATE,
    ADD_COMPONENT_PRODUCT_FORM,
    MARK_ON_DELETE_COMPONENT_PRODUCT_FORM,

    SET_WASTE_PERCENTAGE,
    SET_CONTENT_PERCENTAGE,

    SET_PRODUCT_ID,
    SET_NEW_PRODUCT_NAME,
    SET_IS_CREATE_PRODUCT,
}
