export enum ComponentFormActionType {
    SET_FORM_STATE = 'SET_FORM_STATE',
    SET_COMPONENT_ID = 'SET_COMPONENT_ID',
    SET_COMPONENT_TYPE_ID = 'SET_COMPONENT_TYPE_ID',
    SET_COMPONENT_NAME = 'SET_COMPONENT_NAME',
    SET_SUBMIT_ACTION_TYPE = 'SET_SUBMIT_ACTION_TYPE',

    SET_COMPONENT_PRODUCT_FORM_STATE = 'SET_COMPONENT_PRODUCT_FORM_STATE',
    ADD_COMPONENT_PRODUCT_FORM = 'ADD_COMPONENT_PRODUCT_FORM',
    SET_COMPONENT_PRODUCT_ACTION_TYPE = 'SET_COMPONENT_PRODUCT_ACTION_TYPE',

    SET_WASTE_PERCENTAGE = 'SET_WASTE_PERCENTAGE',
    SET_CONTENT_PERCENTAGE = 'SET_CONTENT_PERCENTAGE',

    SET_PRODUCT_ID = 'SET_PRODUCT_ID',
    SET_NEW_PRODUCT_NAME = 'SET_NEW_PRODUCT_NAME',
    SET_SUBMIT_PRODUCT_ACTION_TYPE = 'SET_SUBMIT_PRODUCT_ACTION_TYPE',

    CAST_CONTENTS_TO_VALID_PERCENTAGES = 'CAST_CONTENTS_TO_VALID_PERCENTAGES',
}

export enum ComponentDetailActionType {
    SET_COMPONENT_STATE = 'SET_COMPONENT_STATE',
}