export enum IngredientFormActionType {
    SET_FORM_STATE = 'SET_FORM_STATE',
    SET_INGREDIENT_ID = 'SET_INGREDIENT_ID',
    SET_INGREDIENT_TYPE_ID = 'SET_INGREDIENT_TYPE_ID',
    SET_INGREDIENT_NAME = 'SET_INGREDIENT_NAME',
    SET_SUBMIT_ACTION_TYPE = 'SET_SUBMIT_ACTION_TYPE',

    SET_INGREDIENT_PRODUCT_FORM_STATE = 'SET_INGREDIENT_PRODUCT_FORM_STATE',
    ADD_INGREDIENT_PRODUCT_FORM = 'ADD_INGREDIENT_PRODUCT_FORM',
    SET_INGREDIENT_PRODUCT_ACTION_TYPE = 'SET_INGREDIENT_PRODUCT_ACTION_TYPE',

    SET_WASTE_PERCENTAGE = 'SET_WASTE_PERCENTAGE',
    SET_CONTENT_PERCENTAGE = 'SET_CONTENT_PERCENTAGE',

    SET_PRODUCT_ID = 'SET_PRODUCT_ID',
    SET_NEW_PRODUCT_NAME = 'SET_NEW_PRODUCT_NAME',
    SET_SUBMIT_PRODUCT_ACTION_TYPE = 'SET_SUBMIT_PRODUCT_ACTION_TYPE',

    CAST_CONTENTS_TO_VALID_PERCENTAGES = 'CAST_CONTENTS_TO_VALID_PERCENTAGES',
}

export enum IngredientDetailActionType {
    SET_INGREDIENT_STATE = 'SET_INGREDIENT_STATE',
}